dashboard:
  pattern:  /dashboard
  defaults: { _controller:RJCDiakonia:Dashboard:index }

dashboard_calendar:
  pattern:  /dashboard/calendar
  defaults: { _controller:RJCDiakonia:Dashboard:calendar }

people:
   pattern: /people
   defaults: { _controller:RJCDiakonia:People:index }

song:
   pattern: /song
   defaults: { _controller:RJCDiakonia:Song:index }

song_create:
   pattern: /song/create
   defaults: { _controller:RJCDiakonia:Song:create }

song_edit:
   pattern: /song/edit/{id}
   defaults: { _controller:RJCDiakonia:Song:edit }

song_view:
   pattern: /song/view/{id}
   defaults: { _controller:RJCDiakonia:Song:view }