dashboard:
  pattern:  /dashboard
  defaults: { _controller:RJCDiakonia:Dashboard:index }

dashboard_calendar:
  pattern:  /dashboard/calendar
  defaults: { _controller:RJCDiakonia:Dashboard:calendar }

people:
   pattern: /people
   defaults: { _controller:RJCDiakonia:People:index }