imports:
    - { resource: parameters.ini }
    - { resource: security.yml }
    - { resource: "@RJCDiakoniaBundle/Resources/config/menu.xml" }

framework:
    charset:       UTF-8
    error_handler: null
    csrf_protection:
        enabled: true
        secret: %csrf_secret%
    router:        { resource: "%kernel.root_dir%/config/routing.yml" }
    validation:    { enabled: true, annotations: true }
    templating:    { engines: ['twig'] } #assets_version: SomeVersionScheme
    session:
        default_locale: %locale%
        lifetime:       3600
        auto_start:     true

# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%
    form:
        resources: [RJCDiakoniaBundle::form.html.twig]

# Assetic Configuration
assetic:
    debug:          %kernel.debug%
    use_controller: false
    filters:
        cssrewrite: ~
        closure:    ~

# Doctrine Configuration
doctrine_mongo_db:
    connections:
      default:
        server: mongodb://localhost:27017
        options:
          connect: true
    default_database: diakonia
    document_managers:
        default:
            mappings:
                FOSUser: ~
                RJCDiakonia: ~
            metadata_cache_driver: array
      
#doctrine:
#    dbal:
#        default_connection: default
#        connections:
#            default:
#                driver:   %database_driver%
#                host:     %database_host%
#                dbname:   %database_name%
#                user:     %database_user%
#                password: %database_password%

#    orm:
#        auto_generate_proxy_classes: %kernel.debug%
#        default_entity_manager: default
#        entity_managers:
#            default:
#                mappings:
#                    AcmeDemo: ~

# Swiftmailer Configuration
swiftmailer:
    transport: %mailer_transport%
    host:      %mailer_host%
    username:  %mailer_user%
    password:  %mailer_password%

jms_security_extra:
    secure_controllers:  true
    secure_all_services: false


#Menu Configuration
knplabs_menu:
    twig: true

#Pagination Configuration
knplabs_paginator:
    templating: ~

#User Configuration
fos_user:
    db_driver: mongodb
    provider_key: main
    class:
        model:
            user: RJC\DiakoniaBundle\Document\User
    group:
        class:
            model: RJC\DiakoniaBundle\Document\Group

#Snappy Configuration
knplabs_snappy:
    pdf: ~

parameters:
    knplabs.snappy.pdf.executable: /Development/Diakonia/bin/wkhtmltopdf